# MobileNetV3-Small backbone configuration
mode: small
# Pretrained backbone weights (downloaded separately)
pretrained_weights: mobilenetv3-small-55df8e1f.pth # Expected in pretrained_backbones/
cfgs:
  # k, t, c, SE, HS, s
  - [3, 1, 16, 1, 0, 2]
  - [3, 4.5, 24, 0, 0, 2]
  - [3, 3.67, 24, 0, 0, 1]
  - [5, 4, 40, 1, 1, 2]
  - [5, 6, 40, 1, 1, 1]
  - [5, 6, 40, 1, 1, 1]
  - [5, 3, 48, 1, 1, 1]
  - [5, 3, 48, 1, 1, 1]
  - [5, 6, 96, 1, 1, 2]
  - [5, 6, 96, 1, 1, 1]
  - [5, 6, 96, 1, 1, 1]
