# MobileNetV3-Large backbone configuration
mode: large
# Pretrained backbone weights (downloaded separately)
pretrained_weights: mobilenetv3-large-1cd25616.pth # Expected in pretrained_backbones/
cfgs:
  # k, t, c, SE, HS, s
  - [3, 1, 16, 0, 0, 1]
  - [3, 4, 24, 0, 0, 2]
  - [3, 3, 24, 0, 0, 1]
  - [5, 3, 40, 1, 0, 2]
  - [5, 3, 40, 1, 0, 1]
  - [5, 3, 40, 1, 0, 1]
  - [3, 6, 80, 0, 1, 2]
  - [3, 2.5, 80, 0, 1, 1]
  - [3, 2.3, 80, 0, 1, 1]
  - [3, 2.3, 80, 0, 1, 1]
  - [3, 6, 112, 1, 1, 1]
  - [3, 6, 112, 1, 1, 1]
  - [5, 6, 160, 1, 1, 2]
  - [5, 6, 160, 1, 1, 1]
  - [5, 6, 160, 1, 1, 1]
