# Dataset Configuration
name: UAVid
dataset_config_file: configs/UAVid_info.json # Relative path (project-root relative)
num_classes: 8
cropsize: [1024, 1024]
dataset_path: ${env:DATA_ROOT:} # Env override + fallback
ignore_idx: 255
seed: 0
class_weights: [
    2.8149201869965, # road
    6.9850029945374, # sidewalk
    3.7890393733978, # building
    9.9428062438965, # wall
    9.7702074050903, # fence
    9.5110931396484, # pole
    10.311357498169, # traffic light
    10.026463508606, # traffic sign
  ]
# Note: shuffle is handled in DataLoader, not here
