# Dataset Configuration
name: uavid
config_file: configs/UAVid_info.json # Relative path (project-root relative)
num_classes: 8
cropsize: [1024, 1024]
dataset_path: ${env:DATA_ROOT:} # Env override + fallback
ignore_idx: 255
seed: 0
class_weights: [
    1.60, # clutter
    1.00, # building
    2.26, # road
    15.31, # static car
    1.43, # tree
    2.48, # vegetation
    20.00, # human
    18.89, # moving car
  ]
# Note: shuffle is handled in DataLoader, not here
